# 4章 線形代数

例4-1 Pythonでリストを使ってベクトルを宣言する例

In [ ]:
v = [3, 2]
v

[3, 2]

例4-2 NumPyを使ってPythonでベクトルを宣言する例

In [ ]:
import numpy as np
v = np.array([3, 2])
print(v)

[3 2]


例4-3 PythonでNumPyを使って3次元ベクトルを宣言する例

In [ ]:
import numpy as np
v = np.array([4, 1, 2])
print(v)

[4 1 2]


例4-4 PythonでNumPyを使って5次元のベクトルを宣言する例

In [ ]:
import numpy as np
v = np.array([6, 1, 5, 8, 3])
print(v)

[6 1 5 8 3]


例4-5 PythonでNumPyを使って2つのベクトルを加算する例

In [ ]:
from numpy import array

v = array([3,2])
w = array([2,-1])

# ベクトルを足し合わせる
v_plus_w = v + w

# 加算したベクトルを出力する
print(v_plus_w)

[5 1]


例4-6 NumPyを使ってPythonでベクトルを実数倍にスケーリングする例

In [ ]:
from numpy import array

v = array([3,1])

# ベクトルをスケーリングする
scaled_v = 2.0 * v

# スケーリングしたベクトルを表示する
print(scaled_v)

[6. 2.]


例4-7 NumPyによる行列とベクトルの積

In [ ]:
from numpy import array

# iハットとjハットの基底ベクトルの行列を生成する
basis = array(
    [[3, 0],
     [0, 2]]
 )

# ベクトルvを宣言する
v = array([1,1])

# 内積によりvを変換して新たなベクトルを作り出す
new_v = basis.dot(v)

print(new_v)

[3 2]


例4-8 基底ベクトルを個別に扱って変換する例

In [ ]:
from numpy import array

# iハットとjハットを宣言する
i_hat = array([2, 0])
j_hat = array([0, 3])

# iハットとjハットを使って基底ベクトルの行列を作成する
# 行を列に転置する必要がある
basis = array([i_hat, j_hat]).transpose()

# ベクトルvを宣言する
v = array([1,1])

# 内積によりvを変換して新たなベクトルを作り出す
new_v = basis.dot(v)

print(new_v)

[2 3]


例4-9 NumPyを使ってベクトルを変換する例

In [ ]:
from numpy import array

# iハットとjハットを宣言する
i_hat = array([2, 0])
j_hat = array([0, 3])

# iハットとjハットを使って基底ベクトルの行列を作成する
# 行を列に転置する必要がある
basis = array([i_hat, j_hat]).transpose()


# ベクトルvを宣言する
v = array([2,1])

# 内積によりvを変換して新たなベクトルを作り出す
new_v = basis.dot(v)

print(new_v)

[4 3]


例4-10 複雑な変換の例

In [ ]:
from numpy import array

# iハットとjハットを宣言する
i_hat = array([2, 3])
j_hat = array([2, -1])

# iハットとjハットを使って基底ベクトルの行列を作成する
# 行を列に転置する必要がある
basis = array([i_hat, j_hat]).transpose()

# ベクトルvを宣言する
v = array([2,1])

# 内積によりvを変換して新たなベクトルを作り出す
new_v = basis.dot(v)

print(new_v)

[6 5]


例4-11 2つの変換を統合する例

In [ ]:
from numpy import array

# 変換1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# 変換2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# 変換を統合する
combined = transform2 @ transform1

# 試しに表示する
print("COMBINED MATRIX:\n {}".format(combined))

COMBINED MATRIX:
 [[ 1 -1]
 [ 1  0]]


In [ ]:
v = array([1, 2])
print(combined.dot(v))

[-1  1]


例4-12 変換を逆順に適用する例

In [ ]:
from numpy import array

# 変換1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# 変換2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# 最初にせん断を適用し、その後に回転を適用する
combined = transform1 @ transform2

# 試しに表示する
print("COMBINED MATRIX:\n {}".format(combined))

COMBINED MATRIX:
 [[ 0 -1]
 [ 1  1]]


In [ ]:
v = array([1, 2])
print(combined.dot(v))

[-2  3]


例4-13 行列式を求める例

In [ ]:
from numpy.linalg import det
from numpy import array

i_hat = array([3, 0])
j_hat = array([0, 2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

6.0


例4-14 せん断の行列式を求める例

In [ ]:
from numpy.linalg import det
from numpy import array

i_hat = array([1, 0])
j_hat = array([1, 1])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

1.0


例4-15 負の値になる行列式の例

In [ ]:
from numpy.linalg import det
from numpy import array

i_hat = array([-2, 1])
j_hat = array([1, 2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

-5.000000000000001


例4-16 行列式が0となる例

In [ ]:
from numpy.linalg import det
from numpy import array

i_hat = array([3, -1.5])
j_hat = array([-2, 1])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

0.0


例4-17 SymPyを使って逆行列と単位行列を確認する例

In [ ]:
from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

# 行列Aとその逆行列の行列積を取り、
# 単位行列を得る
inverse = A.inv()
inverse

Matrix([
[-1/2,  0,  1/3],
[11/2, -2, -4/3],
[  -2,  1,  1/3]])

In [ ]:
identity = inverse * A
identity

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [ ]:
print("INVERSE: {}".format(inverse))
print("IDENTITY: {}".format(identity))

INVERSE: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
IDENTITY: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


例4-18 NumPyを使って連立方程式を求める例

In [ ]:
from numpy import array
from numpy.linalg import inv

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = array([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = array([
    44,
    56,
    72
])

X = inv(A).dot(B)
print(X)

[ 2. 34. -8.]


例4-19 SymPyを使って連立方程式を求める例

In [ ]:
from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = Matrix([
    44,
    56,
    72
])

X = A.inv() * B
X

Matrix([
[ 2],
[34],
[-8]])

例4-20 NumPyで行列分解を実行する例

In [ ]:
from numpy import array
from numpy.linalg import eig

A = array([
    [1, 2],
    [4, 5]
])

eigenvals, eigenvecs = eig(A)

print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)

EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


例4-21 NumPyを使って行列分解と再構築する例

In [ ]:
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])

eigenvals, eigenvecs = eig(A)

print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)

print("\nREBUILD MATRIX")
Q = eigenvecs
R = inv(Q)
L = diag(eigenvals)
B = Q @ L @ R

print(B)

EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]

REBUILD MATRIX
[[1. 2.]
 [4. 5.]]
